# Deep Learning With PyTorch: A 60 Minute Blitz

## What is PyTorch?
pyTorch is a Python-based scientific computing package serving two broad purposes:
- A replaement for NumPy to use the power of GPUs and other accelerators.
- An automatic differentiation library that is useful to implement neural networks.

## Goal of this Tutorial:
- Understand PyTorch's Tensor library and neural networks at a high level.
- Train a small neural network to classify images

[torch](https://github.com/pytorch/pytorch) and [torchvision](https://github.com/pytorch/vision) is required.

## Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model's parameters.

Tensors are similarly to NumPy's ndarrays, except that tensors can run on GPUs or other specialized hardware to accelerate computing. Familiarity with ndarrays will translate to Tensor API.

In [1]:
import torch
import numpy as np

## Tensor Initialization

Tensors can be initialized in various ways. Take a look at the following examples:

### Directly from data
Tensors can be created directly from data. The data type is automatically inferred.

In [2]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

### From a NumPy Array
Tensors can be created from NumPy arrays (and vice versa - see [Bridge with NumPy](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label)).

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

### From another tensor:
The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

In [4]:
x_ones = torch.ones_like(x_data)
print (f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print (f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0059, 0.9140],
        [0.5774, 0.9073]]) 



### With random or constant values:
`shape` is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.

In [6]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print (f"Random Tensor: \n {rand_tensor} \n")
print (f"Ones Tensor: \n {ones_tensor} \n")
print (f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.6581, 0.1051, 0.5978],
        [0.5745, 0.5635, 0.1125]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



## Tensor Attributes
Tensor attributes describe their shapes, datatype, and the device on which they are stored.

In [7]:
tensor = torch.rand(3, 4)

print (f"Shape of tensor: {tensor.shape}")
print (f"Datatype of tensor: {tensor.dtype}")
print (f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Tensor Operations
Over 100 tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random sampling, and more are comprehensively described [here](https://pytorch.org/docs/stable/torch.html).

Each of them can be run on the GPU (at typically higher speeds than on a CPU). If you're using Colab, allocate a GPU by going to Edit > Notebook Settings.

In [8]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print (f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


Try out some of the operations from the list. If you're familiar with the NumPy API, you'll find the Tensor API a breeze to use.

### Standard numpy-like indexing and slicing:

In [9]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print (tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### Joining tensors
We can use `torch.cat` to concatenate a sequence of tensors along a given dimension. See also [torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html), another tensor joining op that is subtly different from `torch.cat`.

In [10]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print (t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


### Multiplying tensors

In [11]:
# This computes the element-wise product
print (f"tensor.mul(tensor)\n{tensor.mul(tensor)}\n")
# Alternative syntax:
print (f"tensor * tensor\n {tensor*tensor}")

tensor.mul(tensor)
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor * tensor
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


This computes the matrix multiplication between two tensors

In [12]:
print (f"tensor.matmul(tensor.T)\n{tensor.matmul(tensor.T)}\n")
# Alternative syntax:
print (f"tensor @ tensor.T\n {tensor @ tensor.T}")

tensor.matmul(tensor.T)
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

tensor @ tensor.T
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


### In-place operations
Operations that have a `_` suffix are in-place. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

In [13]:
print (tensor, "\n")
tensor.add_(5)
print (tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


Note:
In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.

## Bridge with NumPy
Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

## Tensor to NumPy array

In [14]:
t = torch.ones(5)
print (f"t: {t}")
n = t.numpy()
print (f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.

In [16]:
t.add_(1)
print (f"t: {t}")
print (f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


## NumPy array to Tensor

In [17]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor.

In [18]:
np.add(n, 1, out=n)
print (f"t: {t}")
print (f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
