In [1]:
# Pytorch provides an auto-differentiation functionality.

In [2]:
import torch

In [3]:
# Create a tensor
x = torch.tensor([[1,2],[3,4]],requires_grad=True,dtype=torch.float64)
print (x)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64, requires_grad=True)


In [4]:
# Do an operation on the tensor
y = x-2
print (y)
# y was created as a result of an operation, so it has a grad_fn

tensor([[-1.,  0.],
        [ 1.,  2.]], dtype=torch.float64, grad_fn=<SubBackward0>)


In [5]:
print (y.grad_fn)

In [6]:
print (x.grad_fn)

None


In [7]:
y.grad_fn

In [8]:
y.grad_fn.next_functions[0][0]

In [9]:
y.grad_fn.next_functions[0][0].variable

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64, requires_grad=True)

In [10]:
z=y*y*3
a = z.mean()

print (z)
print (a)

tensor([[ 3.,  0.],
        [ 3., 12.]], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor(4.5000, dtype=torch.float64, grad_fn=<MeanBackward0>)


In [11]:
## Gradients
# Backprop
a.backward()

In [12]:
print (x.grad)

tensor([[-1.5000,  0.0000],
        [ 1.5000,  3.0000]], dtype=torch.float64)


In [13]:
x=torch.randn(3,requires_grad=True)

y = x*2
i = 0
while y.data.norm() <1000:
    y = y*2
    i += 1
    
print (y)

tensor([-1278.3754, -1204.7560,  -928.7454], grad_fn=<MulBackward0>)


In [14]:
gradients = torch.FloatTensor([0.1,1.0,0.0001])
y.backward(gradients)

print (x.grad)

tensor([4.0960e+02, 4.0960e+03, 4.0960e-01])


In [15]:
print (i)

11


In [16]:
## Inference

In [17]:
n=3

In [18]:
x = torch.arange(1., n+1, requires_grad=True)
w = torch.ones(n, requires_grad=True)
z = w@x
z.backward()
print (x.grad, w.grad, sep='\n')

tensor([1., 1., 1.])
tensor([1., 2., 3.])


In [19]:
# Only w that allows gradient accumulation
x = torch.arange(1., n+1, requires_grad=False)
w = torch.ones(n, requires_grad=True)
z = w@x
z.backward()
print (x.grad, w.grad, sep='\n')

None
tensor([1., 2., 3.])


In [20]:
x = torch.arange(1., n+1, requires_grad=False)
w = torch.ones(n, requires_grad=True)

with torch.no_grad(): # all tensors will not have gradients
    z = w@x

try:
    z.backward() # z has no gradient to accumulate and so will throw error
except RuntimeError as e:
    print ("Runtime Error!")
    print (e)

Runtime Error!
element 0 of tensors does not require grad and does not have a grad_fn
