In [3]:
from res.sequential_tasks import EchoData
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1);

In [4]:
batch_size = 5
echo_step = 3
series_length = 20_000
BPTT_T = 20

train_data = EchoData(
    echo_step=echo_step,
    batch_size=batch_size,
    series_length=series_length,
    truncated_length=BPTT_T
)
total_values_in_one_chunk = batch_size*BPTT_T
train_size = len(train_data)

test_data = EchoData(
    echo_step=echo_step,
    batch_size=batch_size,
    series_length=series_length,
    truncated_length=BPTT_T
)
test_size = len(test_data)

In [5]:
# Print first 20 timesteps of the first sequence to see the echo data:
print ('(1st input sequence) x:', *train_data.x_batch[0, :20], '...')
print ('(1st target sequence) x:', *train_data.y_batch[0, :20], '...')

(1st input sequence) x: 0 1 0 1 0 1 0 1 1 0 1 0 0 1 0 1 0 0 0 0 ...
(1st target sequence) x: 0 0 0 0 1 0 1 0 1 0 1 1 0 1 0 0 1 0 1 0 ...


In [6]:
# batch_size different sequences are created:
print('x_batch:', *(str(d)[1:-1] + ' ...' for d in train_data.x_batch[:, :20]), sep='\n')
print('x_batch size:', train_data.x_batch.shape)
print()
print('y_batch:', *(str(d)[1:-1] + ' ...' for d in train_data.y_batch[:, :20]), sep='\n')
print('y_batch size:', train_data.y_batch.shape)

x_batch:
0 1 0 1 0 1 0 1 1 0 1 0 0 1 0 1 0 0 0 0 ...
0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 ...
1 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 ...
1 0 1 1 1 1 1 0 0 1 0 0 0 1 1 0 0 1 0 0 ...
1 0 0 1 1 1 1 0 0 0 0 1 1 1 1 1 1 0 0 0 ...
x_batch size: (5, 20000)

y_batch:
0 0 0 0 1 0 1 0 1 0 1 1 0 1 0 0 1 0 1 0 ...
0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 1 ...
0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 0 1 1 0 0 ...
0 0 0 1 0 0 1 1 1 1 0 0 0 0 1 1 1 1 1 1 ...
y_batch size: (5, 20000)


In [7]:
# In order to use RNNs data is organized temporally
# Chunks of size [batch_size, T, feature_dim]
print ('x_chunks', *train_data.x_chunks[0].squeeze(), sep='\n')
print ('1st x_chunk size: ', train_data.x_chunks[0].shape)
print ()
print ('y_chunks', *train_data.y_chunks[0].squeeze(), sep='\n')
print ('1st y_chunk size: ', train_data.y_chunks[0].shape)

x_chunks
[0 1 0 1 0 1 0 1 1 0 1 0 0 1 0 1 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
[1 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0]
[1 0 1 1 1 1 1 0 0 1 0 0 0 1 1 0 0 1 0 0]
[1 0 0 1 1 1 1 0 0 0 0 1 1 1 1 1 1 0 0 0]
1st x_chunk size:  (5, 20, 1)

y_chunks
[0 0 0 0 1 0 1 0 1 0 1 1 0 1 0 0 1 0 1 0]
[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 1]
[0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 0 1 1 0 0]
[0 0 0 1 0 0 1 1 1 1 0 0 0 0 1 1 1 1 1 1]
1st y_chunk size:  (5, 20, 1)


In [8]:
class SimpleRNN(nn.Module):
    def __init__(self, input_size, rnn_hidden_size, output_size):
        super().__init__()
        self.rnn_hidden_size = rnn_hidden_size
        self.rnn = torch.nn.RNN(
            input_size = input_size,
            hidden_size = rnn_hidden_size,
            num_layers = 1,
            nonlinearity = 'relu',
            batch_first = True
        )
        self.linear = torch.nn.Linear(
            in_features = rnn_hidden_size,
            out_features = 1
        )
        
    def forward(self, x, hidden):
        x, hidden = self.rnn(x, hidden)
        x = self.linear(x)
        return x, hidden

In [9]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [10]:
def train(hidden):
    model.train()
    
    correct = 0
    for batch_idx in range(train_size):
        data, target = train_data[batch_idx]
        data, target = torch.from_numpy(data).float().to(device), torch.from_numpy(target).float().to(device)
        optimizer.zero_grad()
        if hidden is not None:
            hidden.detach_()
        logits, hidden = model(data, hidden)
        loss = criterion(logits, target)
        loss.backward()
        optimizer.step()
        
        pred = (torch.sigmoid(logits) > 0.5)
        correct += (pred == target.byte()).int().sum().item()/total_values_in_one_chunk
        
    return correct, loss.item(), hidden

In [12]:
def test(hidden):
    model.eval()
    correct = 0
    
    with torch.no_grad():
        for batch_idx in range(test_size):
            data, target = test_data[batch_idx]
            data, target = torch.from_numpy(data).float().to(device), torch.from_numpy(target).float().to(device)
            logits, hidden = model(data, hidden)

            pred = (torch.sigmoid(logits) > 0.5)
            correct += (pred == target.byte()).int().sum().item()/total_values_in_one_chunk
        
    return correct

In [13]:
feature_dim = 1 # Scalar series, 1 dimensional
h_units = 4

model = SimpleRNN(
    input_size = 1,
    rnn_hidden_size = h_units,
    output_size = feature_dim
).to(device)
hidden = None

criterion = torch.nn.BCEWithLogitsLoss()
optimizer = torch.optim.RMSprop(model.parameters(), lr=0.001)

In [14]:
n_epochs = 5
epoch = 0

while epoch < n_epochs:
    correct, loss, hidden = train(hidden)
    epoch += 1
    train_accuracy = float(correct)*100/train_size
    print(f'Train Epoch: {epoch}/{n_epochs}, Loss: {loss:.3f}, accuracy: {train_accuracy:.1f}%')
    
# Test
correct = test(hidden)
test_accuracy = float(correct)*100/test_size
print (f'Test accuracy: {test_accuracy:.1f}%')

Train Epoch: 1/5, Loss: 0.485, accuracy: 60.1%
Train Epoch: 2/5, Loss: 0.037, accuracy: 89.6%
Train Epoch: 3/5, Loss: 0.000, accuracy: 100.0%
Train Epoch: 4/5, Loss: 0.000, accuracy: 100.0%
Train Epoch: 5/5, Loss: 0.000, accuracy: 100.0%
Test accuracy: 100.0%


In [15]:
# Echoing
my_input = torch.empty(1,100,1).random_(2).to(device)
hidden = None
my_out, _ = model(my_input, hidden)
print (my_input.view(1, -1).byte(), (my_out > 0).view(1,-1), sep='\n')

tensor([[1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
         0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
         0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
         0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
         1, 1, 0, 0]], device='cuda:0', dtype=torch.uint8)
tensor([[ True,  True, False, False,  True,  True,  True,  True, False, False,
          True,  True,  True,  True,  True,  True, False,  True,  True, False,
         False,  True, False, False,  True,  True,  True, False,  True, False,
         False,  True,  True, False,  True,  True,  True,  True, False, False,
          True,  True, False, False, False, False,  True,  True,  True, False,
          True, False, False,  True,  True, False,  True,  True, False,  True,
         False, False,  True,  True,  True, False,  True,  True, False,  True,
          True,  True,  True, False, False, False, False, False,